### PR TITLE
Differential uprating

### PR DESCRIPTION
**Pull request by HughParsonage**

### CODE REVIEW

**Comment by youncg81** [comment]
Some of this code is going to be a learning experience for me! I will have a look with fresh eyes on Monday.

**Comment by youncg81** [comment]
I’ve had a look at the differential uprating data and code. I think it all looks pretty good, but I have a couple of concerns with the underlying data that I think we should adjust for.

First, there is a lot of messiness at the bottom, and the start/end years are really important here. Interestingly, not necessarily because of the 1213 tax cuts. Also, top coding in the 2% file is obviously creating issues for the growth at the top.  Both of these issues should be adjusted by applying a smoothing function/trendline.

**Comment by youncg81** [comment]
A test that should be added is to see how much, if any 'overtaking' there is from projecting forward 10 years. So what % people end up in a higher decile in 2023-24 than they were in 2013-14. I think the smoothing function suggested above will also help this.

**Comment by youncg81** [comment]
There should also be a check that the methodology is mean-preserving, so aggregate/average wages are the same with or without differential uprating

**Comment by HughParsonage** [comment]
Image of smooth

**Comment by HughParsonage** [comment]
span045-uprate-factor

**Comment by HughParsonage** [comment]
I've added a test that the differential uprate function is (strictly) mean-preserving.

I expect it will fail ($46,867.83 vs $46,538.86. Failure of a test is a great thing: it tells us what to do next. What do you think? Should we:

- Amend the test to weaken the condition that averages should inflate the same?
- Amend the function to lock the averages?

**Comment by HughParsonage** [comment]
@youncg81 if you're fine with this test, I'll close and merge.

**Comment by youncg81** [comment]
Hey Hugh, sorry for the late reply. On the mean preservation issue, I think we should weaken the test. My guess is that using the smoothing function lead to failing the mean preserving test. 

The difference you quote is less than 1 per cent - which I think is going forward two years? Small, but something to keep an eye on. What is the wedge if we project forward 10 years?

**Comment by HughParsonage** [comment]
## Means are strictly unequal, but close
Also less than 1%.

```r
library(grattan)
library(taxstats)
salaries_1314 <- sample_file_1314$Sw_amt

salaries_2324_vanilla <- wage_inflator(salaries_1314, from_fy = "2013-14", to_fy = "2023-24")
salaries_2324_differe <- differentially_uprate_wage(salaries_1314, from_fy = "2013-14", to_fy = "2023-24")

mean(salaries_1314_vanilla)
# [1] 53883.85
mean(salaries_1314_differe)
# [1] 53713.26

mean(salaries_1314_differe) / mean(salaries_1314_vanilla)
# [1] 0.996834
```

## Use a t-test
So the solution I came up with was using a t.test. If the null hypothesis (that the means are equal) cannot be rejected, the test passes:

```r
t_test <- 
    stats::t.test(salaries_1314_vanilla, salaries_1314_differe, conf.level = 0.66) %>%
    broom::tidy(.)

  expect_gt(t_test$p.value, 0.05)
```

**Pull request merged**
