### PR TITLE
General inflator.

### LINKED ISSUE #22: Improve inflation adjustment function
Hi Hugh,

It would be great if the price index called by the inflation adjustment function could readily be changed. For my use, I'd like to run the function over a construction price index series.

I need to get this done by 29/08 at the absolute latest, so if you don't get a chance to make the function more flexible, it would be great if you could flag it with me so that I put aside time to write my own. 

Thanks a heap!

The relevant code in my script is: 

_Inflating cost variables_

_Here we only inflate for the second approach - only for those projects that actually make it to the construction phase
We inflate all cost variables in the dataset forward to 2015-Q4 dollars
At the moment we're only using a CPI deflator as that is what is easily available via the ABS SDMX website. However we will move to a deflator based on construction costs._

_We import the inflator function (created by Hugh)_
source("inflator.R")

_Now we write a new inflation function, to convert all cost variables forward to 2015-Q4 dollars_

inflate_using_mid_point_qtr <- function(x){
  cpi_inflator_quarters(x, from_q = Const_mid_point_qtr, to_q = "2015-Q4")
}

### PR DESCRIPTION
**Pull request by HughParsonage**
If tests succeed, will close #22

### CODE REVIEW

**Comment by HughParsonage** [comment]
@lucilled If you are satisfied, you can close the issue. 

You can test this on your local machine by `devtools::install_github("hughparsonage/grattan", "general-inflator")`

**Comment by lucilled** [comment]
Hi Hugh - it didn't work!

I got the errors:

Error : object 'if_else' is not exported by 'namespace:dplyr'
ERROR: lazy loading failed for package 'grattan'

There were also three packages: curl, DBI, digest, of those the
devtools::install_github("hughparsonage/grattan", "general-inflator")
command tried to install which resulted in a warning message - eg:
"Warning: cannot remove prior installation of package ‘curl’".

Any ideas of what to do about this?

Lucille

**Comment by HughParsonage** [comment]
Update those packages

**Comment by lucilled** [comment]
Ah yep that fixed that error... but the code that follows doesn't work. I
tried adapting it to "general-inflator.R" (which doesn't work), and then I
loaded the general-inflator code by copying and pasting it from the
general-inflator code on github. The latter appeared to work, but now I
can't get the original inflation code to work (below) - nor my attempts to
adapt it to the general_inflator function.

Any tips....? I think Brendan wrote this code, so I'll check with him
when's he's back tomorrow.

Lucille

# We import the inflator function (created by Hugh)
source("inflator.R")

# Now we write a new inflation function, to convert all cost variables
forward to 2015-Q4 dollars

inflate_using_mid_point_qtr <- function(x){
  cpi_inflator_quarters(x, from_q = Const_mid_point_qtr, to_q = "2015-Q4")
}

# We do this in a separate dataframe

project_dataset_costs_nominal <- copy(project_dataset)

# We filter out any records where the project never made it to the
construction phase

project_dataset_costs_real <-
  project_dataset %>%
  filter(!is.na(Const_mid_point)) %>%
  setkey(Grattan_record, Qtrs_in_dataset) # ERROR: in setkeyv(x, cols,
verbose = verbose, physical = physical) : x is not a data.table

# Now we inflate forward all cost variable into Q4-2015 dollars

for (j in grep("cost", names(project_dataset_costs_real))){
  set(project_dataset_costs_real, j = j, value =
cpi_inflator_quarters(from_nominal_price = project_dataset_costs_real[[j]],
from_q = project_dataset_costs_real$Const_mid_point_qtr, to_q = "2015-Q4"))
}
    # Error in if (!grepl("([0-9]{4}).(Q[1-4])", from_q) ||
!grepl("([0-9]{4}).(Q[1-4])",  :  missing value where TRUE/FALSE needed

# Now we merge the inflated dataset back into our main dataset, prescribing
the '_real' postscript to all inflated variables

# We select only those inflated cost variables that we need to port across
to the main dataset
project_dataset_costs_real %<>%
  dplyr::select(contains("cost"), Grattan_record, Qtrs_in_dataset)

setkey(project_dataset, Grattan_record, Qtrs_in_dataset)

project_dataset <-
  merge(project_dataset, project_dataset_costs_real, all.x = TRUE, suffixes
= c("","_real"))

# Just remember not all projects reached the construction stage, and
therefore dont get inflated.

**Comment by HughParsonage** [comment]
You need to load library(dtplyr) as well. Sorry o can't run R up here: I'm
away from my computer until tomorrow very late. Any problems, continue
here.

You should try using the function provided by the package rather than the
internals, so we can track and patch bugs.

**Comment by lucilled** [comment]
Hmm yes dplyr is loaded too, but its still not working.
Don't worry about it Hugh! Enjoy the rest of your holiday, we can fix it up
once you're back.

**Pull request merged**
